### ISSUE TITLE
Scout Alarm & Home Assistant?

### ISSUE THREAD

**Issue by shiitbiird** [jordanryanmoore/homebridge-scout#182]
Hey there! I love this plugin and have had zero issues with it for the past two years I've been using it. NONE. Great work on this guy. 

I just made the switch from Homebridge to Homassistant and I'm loving it so far. For my use case, I can't beat the data and fine-tuning you can do on HA... it's really impressive. That said, I'm super reliant on this plugin for my Scout (v1) system and I can't seem to find an integration for it on HA. The [HA Homekit Controller](https://www.home-assistant.io/integrations/homekit_controller/) and [HomeKit Bridge](https://www.home-assistant.io/integrations/homekit_controller/) on Home Assistant won't work because the device flow is in the opposite direction. I'm still getting used to learning HASSIO so my understanding is still rather minimal, but was wondering if you had thought of creating a friendly version or integration of this for the HASSIO platform? Thanks again!! 

-Seth

**Comment by jordanryanmoore** [comment]
I've been meaning to investigate Home Assistant myself, but I haven't taken any time to do so (yet).

It looks like Home Assistant is written in Python. The current Scout API client that I've implemented ([jordanryanmoore/scout-api](https://github.com/jordanryanmoore/scout-api)) only works for TypeScript/JavaScript. Fortunately, it is generated from an OpenAPI spec, so it wouldn't be terribly difficult to move the OpenAPI spec to a separate repository that the TypeScript/JavaScript one can use, as well as a new Python-based client. This is the first step that would need to be taken.

Unfortunately, I can't promise any sort of timeline on this, or that I'll ever get anything done, but I will create an issue in that repository to start on the API piece of it.

**Comment by shiitbiird** [comment]
Awesome, thanks so much for the consideration @jordanryanmoore! Unfortunately, I'm still learning (teaching myself) how to code, but if there is anything I could do on a smaller scale to help make this happen, PLEASE just let me know.

**Comment by jordanryanmoore** [comment]
Another gap is having a language-appropriate client library for [Pusher](https://pusher.com/), which is what Scout uses to publish real-time events for changes to each Scout location. Unfortunately, [Pusher doesn't provide an official Python client](https://pusher.com/docs/channels/channels_libraries/libraries#client-libraries). There is a [community-supported library](https://pusher.com/docs/channels/channels_libraries/libraries#python), but it's in maintenance mode, so I'm a little skeptical of building something on top of it. From what I can see, the challenge of implementing a client for Pusher in Python wouldn't be insurmountable, but it's a component that I was assuming already existed.

Oh, and Python definitely isn't on my top-5 list of languages I'm most proficient in.

**Comment by jordanryanmoore** [comment]
Since this issue really has nothing to do with the Homebridge Scout plug-in itself, I'm going to resolve it. You can follow jordanryanmoore/scout-api#87 for updates.
