### ISSUE TITLE
HomeKit config lost after restarting HomeBridge

### ISSUE THREAD

**Issue by Tom2527** [jordanryanmoore/homebridge-scout#45]
### Description
All user configurations to Scout accessories in the Home app are lost when HomeBridge is restarted

### Reproduction Steps
1. Add ScoutAlarm to the Apple Home app
2. Make some customisations including, but not limited to, assigning Scout accessories to a specific room, adding accessories to scenes, ...
3. Restart HomeBridge

### Expected Behavior
All customizations to Scout accessories should be present. However, they are lost as the accessories are removed from the Home app and re-added. I assume because the plugin deregisters all cached accessories when loading. This cache purge should probably not occur, unless forced by the user when the Scout configuration has changed.

**Comment by jordanryanmoore** [comment]
Does this happen *every* time you restart `homebridge`, or is it possible that it's only after an upgrade of the `homebridge-scout` plugin?

My experience has been that, as long as the plugin isn't changing the services or characteristics of an accessory, any customizations are retained between `homebridge` restarts. In your case (with v1 hardware), every recent update has changed the services and/or characteristics of your accessories.

You are correct that the cache purge *shouldn't* be happening. It was a short-cut that I took to get things working, as the cached accessory data was causing other problems. I'll take another look at it and see if I can avoid doing that.

**Comment by Tom2527** [comment]
It happens with every restart, even without any changes. I do run HomeBridge as a service and restart from the web interface config-ui-x, in case that matters.

**Comment by jordanryanmoore** [comment]
It’s possible the web interface is doing something to aggravate this (since I’m not experiencing this and am not using that package).

I’ll take a closer look…

**Comment by jordanryanmoore** [comment]
I’ve started a major refactor that will address this… but it’s going to take some time.

**Comment by jordanryanmoore** [comment]
I've pushed a change (577e097) that should fix this, but it's a significant refactor, so I'm going to test it for a day or two in my home before releasing it to NPM.

**Comment by Tom2527** [comment]
Great. I’ll test it as well if I get the time.

**Comment by jordanryanmoore** [comment]
I released 0.5.0 with the fix.
