### ISSUE TITLE
Siri intermittently claims (incorrectly) that it can’t arm the security system

### ISSUE THREAD

**Issue by jordanryanmoore** [jordanryanmoore/homebridge-scout#46]
### Description
Siri claims that it can’t arm the security system, but it actually does.

### Reproduction Steps
1. Ask Siri on an iPhone, “Arm my security system.”
2. Siri responds with “Sorry, I wasn’t able to arm your security system. For more details, check the Home app.”
3. Open the Home app, and see that it actually is arming the security system.

### Expected Behavior
I’m assuming Siri should say something to confirm it’s arming the security system, but I don’t have an official HomeKit security system to know exactly what the expected behavior should be.

### Logs
Non-debug logs all appear normal. No errors.

### Screenshots
![7D7E763E-4B36-44FA-A533-E9A05FF04B56](https://user-images.githubusercontent.com/112001/71782164-f5432780-2f8b-11ea-9811-5afb5b4be2e0.png)

### To Do

* [ ] Get a log dump with DEBUG enabled.
* [ ] …?

**Comment by Tom2527** [comment]
It works fine on my system, so doesn’t seem to be related to Scout being unofficial. 
Siri responds that she armed the system to ‘away’.

**Comment by jordanryanmoore** [comment]
This seems to work intermittently for me now… not sure why yet.

**Comment by jordanryanmoore** [comment]
I need to run homebridge with `DEBUG` enabled and see if anything shows up there.

**Comment by Tom2527** [comment]
I experienced this issue once. Couldn't tell what the issue was, but using another device, Siri succeeded so possibly it's a Homekit thing and not related to the plugin.

**Comment by jordanryanmoore** [comment]
I can't seem to reproduce this issue with the latest versions of the plug-in.
