### ISSUE TITLE
Not supporting multiple Homebridge instances

### ISSUE THREAD

**Issue by Tom2527** [jordanryanmoore/homebridge-scout#48]
### Description
When running two completely separate instances of HomeBridge on the same machine, each with their own config.json, the scout plugin does not play nicely. 

### Reproduction Steps
1. Create two instances of homebridge with two config.json files. One configures the scout plugin, the other one doesn't.
2. run them both. 
3. the one with the Scout plugin configured, runs fine. The other one also tries to load all the accessories, but fails. They are however added to (a second) HomeKit but remain non-functional. 

### Expected Behavior
the second homebridge should not load the accessories. However, the plugin seems to load the accessories when the plugin is loaded, not when configured.

### Logs
[1/5/2020, 8:09:36 PM] Loading 0 accessories...
Failed to find plugin to handle accessory Security System
Failed to find plugin to handle accessory Front Door
Failed to find plugin to handle accessory Bedroom Window
Failed to find plugin to handle accessory Garage
Failed to find plugin to handle accessory Kitchen Door
Failed to find plugin to handle accessory Motion Sensor

### Additional Context
I don't know enough about this stuff to know if this is a bug or not. But all my other plugins do not have this behaviour. If they are not configured in the second config.json file, they are not loaded and do not appear in the second HomeKit.
Or is this simply because the plugin is installed globally with the parameter -g?

### To Do

* [ ] Attempt to reproduce the issue.
* [ ] …?

**Comment by jordanryanmoore** [comment]
I might be wrong here, but it sounds like both Homebridge instances are sharing the same cached accessories file. That file is created by Homebridge, not the plugin. 

If this is the only *dynamic* *platform* plugin you are using, that would be why this is the first time it’s been a problem for you. Plugins that require configuring each accessory or static platform plugins won’t have this issue because they don’t get saved to the cached accessories file.

**Comment by jordanryanmoore** [comment]
…or, is it possible that you did have the plugin configured in both for even only one run and then removed it?

**Comment by jordanryanmoore** [comment]
There's nothing going on here that the plug-in can control. There must have been some configuration or cached data that was shared at some point between the two homebridge instances that caused this.
